"""Add status and technical fields to assets

Revision ID: 0e5398229f43
Revises: d63cea1c0501
Create Date: 2026-04-10 13:06:20.456283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e5398229f43'
down_revision = 'd63cea1c0501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('serial', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('mac_address', sa.String(length=17), nullable=True))
        batch_op.add_column(sa.Column('warranty_date', sa.Date(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('assets_sku_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['serial'])
        batch_op.create_unique_constraint(None, ['asset_id'])
        batch_op.drop_column('sku')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('assets_sku_key'), ['sku'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('warranty_date')
        batch_op.drop_column('mac_address')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('status')
        batch_op.drop_column('serial')
        batch_op.drop_column('asset_id')

    # ### end Alembic commands ###
