"""Sync consumable and location fields to supabase

Revision ID: 242df7745352
Revises: 
Create Date: 2026-04-14 17:01:06.111367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242df7745352'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['sku'])
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('location_id')
        batch_op.drop_column('category_id')
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
