"""Add address to locations

Revision ID: 323c4ca7e2fc
Revises: 982355f47a7b
Create Date: 2026-04-17 16:40:07.482553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323c4ca7e2fc'
down_revision = '982355f47a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('locations_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('locations_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('address')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
