"""Fix Consumable table headers

Revision ID: 982355f47a7b
Revises: 335fdbd260cb
Create Date: 2026-04-17 14:56:01.816614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982355f47a7b'
down_revision = '335fdbd260cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
