"""Add supplier_name to AssetItem and Consumable

Revision ID: b8acb80a38d0
Revises: 323c4ca7e2fc
Create Date: 2026-04-20 17:19:42.421304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8acb80a38d0'
down_revision = '323c4ca7e2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=True),
    sa.Column('last_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_name'], ['name'])

    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.String(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_name'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_name')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_name')

    op.drop_table('suppliers')
    op.drop_table('master_items')
    # ### end Alembic commands ###
