"""Sync Locations and Consumables counts

Revision ID: e21bf04209f6
Revises: d3d371f597c9
Create Date: 2026-04-10 17:57:05.751825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21bf04209f6'
down_revision = 'd3d371f597c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.alter_column('min_threshold',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.alter_column('min_threshold',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
